#!/usr/bin/env ruby

require 'git'
puts "starting..............."

Dir.glob('*').select do |directory| 
  puts File.directory? directory
  # next unless File.directory? directory
  puts Dir.exists? File.join(directory, '.git')
  next unless Dir.exists? File.join(directory, '.git')

  g = Git.open directory

  puts "Pulling #{g.current_branch} for #{g.repo}"

  begin
    puts g.pull g.repo, g.current_branch
  rescue StandardError => e
    puts e
  end
end
